language: node_js
node_js:
  - stable

script:
  - npm install
  - npm test
  - npm run build

deploy:
  provider: heroku
  api_key:
    secure: "YOUR ENCRYPTED API KEY"
  edge: true
  project: ./build/
  domain: timerapp.nabeelfarid.surge.sh
  on:
    branch: main
