language: node_js
node_js:
  - stable

script:
  - npm install
  - npm test
  - npm run build

deploy:
  provider: heroku
  app: spacex-bootcamp
  edge: true
  project: ./build/
  on:
    branch: main
